#properties
#spring.datasource.url=jdbc:postgresql://ec2-52-44-166-58.compute-1.amazonaws.com:5432/d2dn1uugt47pgr
#spring.datasource.username=lxdfrmstqtluxa
#spring.datasource.password=d59b74aa3fa6d5ada4da9a0501f3fa51b464e90f0449ebdc3ff4e577aef0a5a0
#spring.datasource.maximumPoolSize=1

#YAML
# troca "=" por ": "
spring:
  datasource:
    url: jdbc:postgres://ec2-52-202-66-191.compute-1.amazonaws.com:5432/dbr5g6l8ha79go
    username: wfvwagksjyyzeg
    password: 3698071efcec88df7e1058cb870215877c2a5a50d25a469287cbeab3fbac4546
    maximumPoolSize: 1
